### ISSUE TITLE
Erreur dans le notebook FR

### ISSUE THREAD

**Issue by drvenabili** [opinionscience/FabriqueLLM#2]
Salut,

C'est un détail mais dans [Fine_tune_avec_falcon_4bit.ipynb](https://github.com/opinionscience/FabriqueLLM/blob/main/falcon/Fine_tune_avec_falcon_4bit.ipynb), dans la cellule sous _installation_ nous lisons :

> En tout premier lieu nous vérifions si nous disposons de suffisamment de mémoire vive **au moins 24go) sinon ce n'est pas la peine de lancer le script.**

alors que la première cellule dit : 
> Ce carnet de code utilise une version déjà ré-entraînée de Falcon-7 : instruct-4-bit. C'est aussi une version plus compacte de Falcon qui devrait pouvoir tourner sur une version gratuite de Google Colab : vous aurez besoin d'environ **10go de Vram**. 

Sinon tout fonctionne nickel, merci pour ce notebook

**Comment by Pclanglais** [comment]
Ah oui bien vu. C'est un résidu de la première version du script (qui ne tournait pas sur 4-bit). C'est corrigé.

**Comment by Pclanglais** [comment]
Ah oui bien vu. C'est un résidu de la première version du script (qui ne tournait pas sur 4-bit). C'est corrigé.
